#		  Resource Source File, Version 2.2
#	     Character Set Definitions for Code Page 852
#
# See the file resource.doc for information on the syntax of this file.
#
# Basic entry format:
#
#	glyph <###> <code>
#	<line 0>
#	<line 1>
#	<line 2>
#	<line 3>
#	<line 4>
#	<line 5>
#
# <###> is the number of the character glyph.  Range 0 to 255.
#
# <code> is "" if no expanded form is supported, or a unique 2-character
# string.  When the form ^!XX is encountered in a string and XX matches
# this 2-character string, the <###> is substitued.  Otherwise, XX is
# output.
#
# <line 0> to <line 5> is exactly six strings.  They specify the bitmap.
# Each string must be exactly 4 characters long.  Non-space characters
# are set bits and space (32 decimal) characters represent reset bits.

# (see rpagebeg.res for glyphs 000 to 127)

glyph 128 "C,"
"*** "
"*   "
"*   "
"*** "
" *  "
"    "

glyph 129 "u:"
"* * "
"    "
"* * "
"* * "
"*** "
"    "

glyph 130 "e'"
"  * "
"*** "
"*** "
"*   "
"*** "
"    "

glyph 131 "a^"
" *  "
"    "
" ** "
"* * "
"*** "
"    "

glyph 132 "a:"
"* * "
"    "
" ** "
"* * "
"*** "
"    "

glyph 133 "uo"
" *  "
"    "
"* * "
"* * "
"*** "
"    "

glyph 134 "c'"
"  * "
"    "
"*** "
"*   "
"*** "
"    "

glyph 135 "c,"
"    "
"*** "
"*   "
"*** "
" *  "
"    "

glyph 136 "l/"
" *  "
" ** "
"*** "
"**  "
" *  "
"    "

glyph 137 "e:"
"* * "
"*** "
"*** "
"*   "
"*** "
"    "

glyph 138 "O\""
" ** "
"*** "
"* * "
"* * "
"*** "
"    "

glyph 139 "o\""
" ** "
"    "
"*** "
"* * "
"*** "
"    "

glyph 140 "i^"
" *  "
"    "
" *  "
" *  "
" *  "
"    "

glyph 141 "Z'"
"  * "
"*** "
" *  "
"*   "
"*** "
"    "

glyph 142 "A:"
"* * "
" *  "
"* * "
"*** "
"* * "
"    "

glyph 143 "C'"
"  * "
"*** "
"*   "
"*   "
"*** "
"    "

glyph 144 "E'"
"  * "
"*** "
"**  "
"*   "
"*** "
"    "

glyph 145 "L'"
"  * "
"*   "
"*   "
"*   "
"*** "
"    "

glyph 146 "l'"
"  * "
" *  "
" *  "
" *  "
" *  "
"    "

glyph 147 "o^"
" *  "
"    "
"*** "
"* * "
"*** "
"    "

glyph 148 "o:"
"* * "
"    "
"*** "
"* * "
"*** "
"    "

glyph 149 "Lv"
"**  "
"*   "
"*   "
"*   "
"*** "
"    "

glyph 150 "lv"
"**  "
" *  "
" *  "
" *  "
" *  "
"    "

glyph 151 "S'"
"  * "
"*** "
" *  "
"  * "
"*** "
"    "

glyph 152 "s'"
"  * "
"    "
"*** "
" ** "
"*** "
"    "

glyph 153 "O:"
"* * "
"*** "
"* * "
"* * "
"*** "
"    "

glyph 154 "U:"
"* * "
"    "
"* * "
"* * "
"*** "
"    "

glyph 155 "Tv"
"**  "
"*** "
" *  "
" *  "
" *  "
"    "

glyph 156 "tv"
"**  "
" *  "
"*** "
" *  "
" ** "
"    "

glyph 157 "L/"
"    "
" ** "
"*** "
"**  "
" ** "
"    "

glyph 158 ""
"* * "
"* * "
" *  "
"* * "
"* * "
"    "

glyph 159 "cv"
"**  "
"    "
"*** "
"*   "
"*** "
"    "

glyph 160 "a'"
"  * "
"    "
" ** "
"* * "
"*** "
"    "

glyph 161 "i'"
"  * "
"    "
" *  "
" *  "
" *  "
"    "

glyph 162 "o'"
"  * "
"    "
"*** "
"* * "
"*** "
"    "

glyph 163 "u'"
"  * "
"    "
"* * "
"* * "
"*** "
"    "

glyph 164 "A,"
"    "
" *  "
"* * "
"*** "
"* * "
"  * "

glyph 165 "a,"
"    "
"    "
" ** "
"* * "
"*** "
"  * "

glyph 166 "Zv"
"**  "
"*** "
" *  "
"*   "
"*** "
"    "

glyph 167 "zv"
"**  "
"    "
"*** "
"**  "
"*** "
"    "

glyph 168 "E,"
"    "
"*** "
"**  "
"*   "
"*** "
"  * "

glyph 169 "e,"
"    "
"*** "
"*** "
"*   "
"*** "
"  * "

glyph 170 ""
"    "
"    "
"*** "
"  * "
"    "
"    "

glyph 171 "z'"
"  * "
"    "
"*** "
"**  "
"*** "
"    "

glyph 172 "Cv"
"**  "
"*** "
"*   "
"*   "
"*** "
"    "

glyph 173 "s,"
"    "
"    "
"*** "
" ** "
"*** "
"  * "

glyph 174 "<<"
"    "
" *  "
"*   "
" *  "
"    "
"    "

glyph 175 ">>"
"    "
"*   "
" *  "
"*   "
"    "
"    "

glyph 176 ""
"* * "
"    "
"* * "
"    "
"* * "
"    "

glyph 177 ""
"* * "
" * *"
"* * "
" * *"
"* * "
" * *"

glyph 178 ""
"*** "
" ***"
"*** "
" ***"
"*** "
" ***"

glyph 179 ""
" *  "
" *  "
" *  "
" *  "
" *  "
" *  "

glyph 180 ""
" *  "
" *  "
"**  "
" *  "
" *  "
" *  "

glyph 181 "A'"
"  * "
" *  "
"* * "
"*** "
"* * "
"    "

glyph 182 "A^"
"*** "
" *  "
"* * "
"*** "
"* * "
"    "

glyph 183 "Ev"
"**  "
"*** "
"**  "
"*   "
"*** "
"    "

glyph 184 "S,"
"    "
"*** "
" *  "
"  * "
"*** "
"  * "

glyph 185 ""
" * *"
" * *"
"** *"
"   *"
"** *"
" * *"

glyph 186 ""
" * *"
" * *"
" * *"
" * *"
" * *"
" * *"

glyph 187 ""
"    "
"    "
"****"
"   *"
"** *"
" * *"

glyph 188 ""
" * *"
" * *"
"** *"
"   *"
"****"
"    "

glyph 189 "Z."
" *  "
"*** "
" *  "
"*   "
"*** "
"    "

glyph 190 "z."
" *  "
"    "
"*** "
"**  "
"*** "
"    "

glyph 191 ""
"    "
"    "
"**  "
" *  "
" *  "
" *  "

glyph 192 ""
" *  "
" *  "
" ***"
"    "
"    "
"    "

glyph 193 ""
" *  "
" *  "
"****"
"    "
"    "
"    "

glyph 194 ""
"    "
"    "
"****"
" *  "
" *  "
" *  "

glyph 195 ""
" *  "
" *  "
" ***"
" *  "
" *  "
" *  "

glyph 196 ""
"    "
"    "
"****"
"    "
"    "
"    "

glyph 197 ""
" *  "
" *  "
"****"
" *  "
" *  "
" *  "

glyph 198 "Av"
"**  "
" *  "
"* * "
"*** "
"* * "
"    "

glyph 199 "av"
"**  "
"    "
" ** "
"* * "
"*** "
"    "

glyph 200 ""
" * *"
" * *"
" * *"
" *  "
" ***"
"    "

glyph 201 ""
"    "
"    "
" ***"
" *  "
" * *"
" * *"

glyph 202 ""
" * *"
" * *"
"** *"
"    "
"****"
"    "

glyph 203 ""
"    "
"    "
"****"
"    "
"** *"
" * *"

glyph 204 ""
" * *"
" * *"
" * *"
" *  "
" * *"
" * *"

glyph 205 ""
"    "
"    "
"****"
"    "
"****"
"    "

glyph 206 ""
" * *"
" * *"
"** *"
"    "
"** *"
" * *"

glyph 207 ""
"    "
"*** "
"* * "
"*** "
"    "
"    "

glyph 208 "d-"
"    "
" ** "
"  * "
" ** "
" ** "
"    "

glyph 209 "D-"
" *  "
" ** "
"*** "
" ** "
" *  "
"    "

glyph 210 "Dv"
"**  "
"**  "
"* * "
"* * "
"**  "
"    "

glyph 211 "E:"
"* * "
"*** "
"**  "
"*   "
"*** "
"    "

glyph 212 "dv"
"**  "
"  * "
"  * "
"*** "
"*** "
"    "

glyph 213 "Nv"
"**  "
"* * "
"*** "
"*** "
"* * "
"    "

glyph 214 "I'"
"  * "
" *  "
" *  "
" *  "
" *  "
"    "

glyph 215 "I^"
" *  "
"    "
" *  "
" *  "
" *  "
"    "

glyph 216 "ev"
"**  "
"*** "
"*** "
"*   "
"*** "
"    "

glyph 217 ""
" *  "
" *  "
"**  "
"    "
"    "
"    "

glyph 218 ""
"    "
"    "
" ***"
" *  "
" *  "
" *  "

glyph 219 ""
"****"
"****"
"****"
"****"
"****"
"****"

glyph 220 ""
"    "
"    "
"    "
"****"
"****"
"****"

glyph 221 "T,"
"    "
"*** "
" *  "
" *  "
" *  "
"  * "

glyph 222 "U."
" *  "
"* * "
"* * "
"* * "
"*** "
"    "

glyph 223 ""
"****"
"****"
"****"
"    "
"    "
"    "

glyph 224 "O'"
"  * "
"*** "
"* * "
"* * "
"*** "
"    "

glyph 225 "Gb"
"**  "
"* * "
"**  "
"* * "
"**  "
"*   "

glyph 226 "O^"
" *  "
"*** "
"* * "
"* * "
"*** "
"    "

glyph 227 "N'"
"  * "
"* * "
"*** "
"* * "
"* * "
"    "

glyph 228 "n'"
"  * "
"    "
"**  "
"* * "
"* * "
"    "

glyph 229 "nv"
"**  "
"    "
"**  "
"* * "
"* * "
"    "

glyph 230 "Sv"
"**  "
"*** "
" *  "
"  * "
"*** "
"    "

glyph 231 "sv"
"**  "
"    "
"*** "
" ** "
"*** "
"    "

glyph 232 "R'"
"  * "
"**  "
"* * "
"**  "
"* * "
"    "

glyph 233 "U'"
"  * "
"    "
"* * "
"* * "
"*** "
"    "

glyph 234 "r'"
"  * "
"    "
"**  "
"*   "
"*   "
"    "

glyph 235 "U\""
" ** "
"* * "
"* * "
"* * "
"*** "
"    "

glyph 236 "y'"
"  * "
"* * "
" ** "
"  * "
" ** "
"    "

glyph 237 "Y'"
"  * "
"* * "
" *  "
" *  "
" *  "
"    "

glyph 238 "t,"
"    "
" *  "
"*** "
" *  "
" ** "
"  * "

glyph 239 ""
" *  "
"**  "
"*   "
"    "
"    "
"    "

glyph 240 ""
"    "
"    "
"*** "
"    "
"    "
"    "

glyph 241 "''"
" ** "
" ** "
"    "
"    "
"    "
"    "

glyph 242 ",,"
"    "
"    "
"    "
"    "
" *  "
" ** "

glyph 243 "VV"
"* * "
"* * "
" *  "
"    "
"    "
"    "

glyph 244 "vv"
"* * "
" *  "
"    "
"    "
"    "
"    "

glyph 245 ""
"*** "
"*   "
"* * "
"  * "
"*** "
"    "

glyph 246 ""
" *  "
"    "
"*** "
"    "
" *  "
"    "

glyph 247 ""
"    "
"    "
"    "
"    "
"  * "
"**  "

glyph 248 ""
"    "
" *  "
"* * "
" *  "
"    "
"    "

glyph 249 ""
"    "
"* * "
"    "
"    "
"    "
"    "

glyph 250 ""
"    "
"    "
" *  "
"    "
"    "
"    "

glyph 251 "u\""
" ** "
"    "
"* * "
"* * "
"*** "
"    "

glyph 252 "Rv"
"**  "
"**  "
"* * "
"**  "
"* * "
"    "

glyph 253 "rv"
"**  "
"    "
"**  "
"*   "
"*   "
"    "

glyph 254 ""
"    "
"*** "
"*** "
"*** "
"    "
"    "

glyph 255 ""
"    "
"    "
"    "
"    "
"    "
"    "


# ------------------------------------------------------------
# Character Set Configuration Table
#
# This table holds the information required to recognize and convert
# tokens, uppercase letters, lowercase letters, etc.

table	CSET

# This item defines the attributes of each character.  Each value is a
# bit mask with the following assignments:
#
#	bit 2^0		lower case letter
#	bit 2^1		upper case letter
#	bit 2^2		same case letter (only one case available),
#			also covers other characters included in
#			tokens (e.g., digits and _ if you like)
#	bit 2^3		calculator number (digit, A-F, -#.,)
#	bit 2^4		whitespace character (space, tab)
#	bit 2^5		newline character
#	bit 2^6		sentence end character (.?!:)
#	bit 2^7		closing punctuation char ()]}"')

# Sentence end characters are what can end a sentence.  Closing
# punctuation characters are what can appear between the end of a
# sentence and the whitespace.

# You can't configure the paragraph break characters.  Sorry, ran out of bits.

CTYPE	list8
 0  0  0  0  0  0  0  0  0 16 32  0  0  0  0  0	# ^@^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 32	# ^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_
16 64 128 8  0  0  0 128 0 128 0  0  8  8  72 0	#  !"#$%&'()*+,-./
12 12 12 12 12 12 12 12 12 12 64  0  0  0  0 64	# 0123456789:;<=>?
 0 10 10 10 10 10 10  2  2  2  2  2  2  2  2  2	# @ABCDEFGHIJKLMNO
 2  2  2  2  2  2  2  2  2  2  2  0  0 128 0  0	# PQRSTUVWXYZ[\]^_
 0  9  9  9  9  9  9  1  1  1  1  1  1  1  1  1	# `abcdefghijklmno
 1  1  1  1  1  1  1  1  1  1  1  0  0 128 0  0	# pqrstuvwxyz{|}~^?
 2  1  1  1  1  1  1  1  1  1  2  1  1  2  2  2
 2  2  1  1  1  2  1  2  1  2  2  2  1  2  0  1
 1  1  1  1  2  1  2  1  2  1  0  1  2  1  0 128
 0  0  0  0  0  2  2  2  2  0  0  0  0  2  1  0
 0  0  0  0  0  0  2  1  0  0  0  0  0  0  0  0 
 1  2  2  2  1  2  2  2  1  0  0  0  0  2  2  0
 2  4  2  2  1  1  2  1  2  2  1  2  1  2  1  0
 0  0  0  0  0  0  0  0  0  0  0  1  2  1  0  0 .


# This item lists the values to be _added to_ each character to
# convert it from upper to lower case.  Non-zero values are only present
# for upper case letters.

TOLOW	list8
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# ^@^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# ^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	#  !"#$%&'()*+,-./
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# 0123456789:;<=>?
 0 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32	# @ABCDEFGHIJKLMNO
32 32 32 32 32 32 32 32 32 32 32  0  0  0  0  0	# PQRSTUVWXYZ[\]^_
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# `abcdefghijklmno
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# pqrstuvwxyz{|}~^?
 7  0  0  0  0  0  0  0  0  0  1  0  0 30 246 247
242 1  0  0  0  1  0  1  0 251 231 1 0 235 0  0
 0  0  0  0  1  0  1  0  1  0  0  0 243 0  0  0
 0  0  0  0  0 235 205 33 245 0 0 0  0  1  0  0
 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0 
 0 255 2 182 0  16 203 181 0 0 0  0  0 17 175 0
66 0  49  1  0  0  1  0  2 58  0 16  0 255 0  0
 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0 .


# This item lists the values to be added to each character to convert
# it from lower to upper case.  Non-zero values are only present for
# lower case letters.

TOUPP	list8
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# ^@^A^B^C^D^E^F^G^H^I^J^K^L^M^N^O
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# ^P^Q^R^S^T^U^V^W^X^Y^Z^[^\^]^^^_
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	#  !"#$%&'()*+,-./
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# 0123456789:;<=>?
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# @ABCDEFGHIJKLMNO
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0	# PQRSTUVWXYZ[\]^_
0 224 224 224 224 224 224 224 224 224 224 224 224 224 224 224	# `abcdefghijklmno
224 224 224 224 224 224 224 224 224 224 224 0 0 0 0 0	# pqrstuvwxyz{|}~^?
 0 25 14 51 10 89  9 249 21 74 0 255 75 0  0  0
 0  0 255 79 5  0 255 0 255 0  0  0 255 0  0 13
21 53 62 70  0 255 0 255 0 255 0 226 0 11  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0 255 0
 0  0  0  0  0  0  0 255 0  0  0  0  0  0  0  0
 1  0  0  0 254 0  0  0 223 0  0  0  0  0  0  0
 0  0  0  0 255 240 0 255 0 0 254 0  1  0 239 0
 0  0  0  0  0  0  0  0  0  0  0 240 0 255 0  0 .
